"""empty message

Revision ID: 804058f28d2f
Revises: 4349dd7c224b
Create Date: 2017-10-06 16:37:47.717526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '804058f28d2f'
down_revision = '4349dd7c224b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('question', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('username', mysql.TEXT(), nullable=False))
    op.drop_column('question', 'content')
    # ### end Alembic commands ###
